### ISSUE TITLE
curious why additional plugins and gems reference was removed recently from the Dockerfile

### ISSUE THREAD

**Issue by lvnilesh** [docker-discourse/docker-discourse#8]
DISCOURSE_ADDITIONAL_PLUGINS 
DISCOURSE_ADDITIONAL_GEMS

https://github.com/indiehosters/docker-discourse/commit/76eba11e1728bb233435b9b3057147f6eb9764b8#diff-3254677a7917c6c01f55212f86c57fbf

**Comment by pierreozoux** [comment]
Hello!

Really sorry, but I had to upgrade...
What are the needed plugins? I guess we could add them to the base image.

Let me know!
